### ISSUE TITLE
Metadata publish broken

### ISSUE THREAD

**Issue by BioWilko** [CLIMB-COVID/elan-nextflow#20]
Change pushed by myself on 2022-03-07 to move manifest publish to `resolve_uploads` instead of `save_manifest` broke metadata publishing due to a poorly thought out pattern. Metadata manually published on 2022-03-08 to allow reconcile to complete.

**Comment by SamStudio8** [comment]
pattern is fine, but i think the glob only works on registered outputs -- the manifest is not listed as an output of resolve_uploads
